### ISSUE TITLE
mappedGenes.csv and mappedReads.csv switched

### ISSUE THREAD

**Issue by christophevandijck** [DataIntellSystLab/KARGA#2]
Hi, 
just one very small comment:
it seems that mappedGenes.csv and mappedReads.csv were accidentally switched in the readme file: 

"inputFileName_KARGA_mappedGenes.csv : a CSV file --one line per read-- with the following fields: Read_Idx, GeneProbability/KmersHitsOnGene/KmersHitsOnAllGenes/KmersTotal, GeneAnnotation.
inputFileName_KARGA_mappedReads.csv : a CSV --one line per ARG-- with the following fields: GeneIdx, PercentGeneCovered, AverageKMerDepth. Note that ARGs with coverage below 1% are not printed; recommended ARG coverage is 80%."

**Comment by DataIntellSystLab** [comment]
fixed!
